//THIS FILE CONTAINS VILE WORDS AND PHRASES. THEY ARE STORED TO ENSURE THEY WILL NOT BE USED IN MESSAGES. VIEW AT YOUR OWN RISK! THIS LIST WAS CREATED BY YOUTUBE
export const badWords = [
  "2 girls 1 cup",
  "2g1c",
  "4r5e",
  "5h1t",
  "5hit",
  "a$$",
  "a$$hole",
  "a_s_s",
  "a2m",
  "a54",
  "a55",
  "a55hole",
  "aeolus",
  "alabama hot pocket",
  "alaskan pipeline",
  "anal impaler",
  "anal leakage",
  "analannie",
  "analprobe",
  "analsex",
  "anilingus",
  "apeshit",
  "ar5e",
  "ass fuck",
  "ass hole",
  "assault",
  "assbag",
  "assbagger",
  "assbandit",
  "assbang",
  "assbanged",
  "assbanger",
  "assbangs",
  "assbite",
  "assblaster",
  "assclown",
  "asscock",
  "asscracker",
  "assface",
  "assfaces",
  "assfuck",
  "assfucker",
  "ass-fucker",
  "assfukka",
  "assgoblin",
  "assh0le",
  "asshat",
  "ass-hat",
  "asshead",
  "assho1e",
  "asshole",
  "assholes",
  "asshopper",
  "asshore",
  "ass-jabber",
  "assjacker",
  "assjockey",
  "asskiss",
  "asskisser",
  "assklown",
  "asslick",
  "asslicker",
  "asslover",
  "assman",
  "assmaster",
  "assmonkey",
  "assmucus",
  "assmunch",
  "assmuncher",
  "assnigger",
  "asspacker",
  "asspirate",
  "ass-pirate",
  "asspuppies",
  "assranger",
  "assshit",
  "assshole",
  "asssucker",
  "asswad",
  "asswhole",
  "asswhore",
  "asswipe",
  "asswipes",
  "auto erotic",
  "autoerotic",
  "axwound",
  "azazel",
  "b!tch",
  "b00bs",
  "b17ch",
  "b1tch",
  "babeland",
  "baby batter",
  "baby juice",
  "badfuck",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "balllicker",
  "bangbros",
  "banger",
  "bareback",
  "barely legal",
  "barenaked",
  "barf",
  "barface",
  "barfface",
  "bastard",
  "bastardo",
  "bastards",
  "bastinado",
  "batty boy",
  "bawdy",
  "bazongas",
  "bazooms",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beardedclam",
  "beastial",
  "beastiality",
  "beatch",
  "beater",
  "beatyourmeat",
  "beaver cleaver",
  "beaver lips",
  "beef curtain",
  "beef curtains",
  "beeyotch",
  "bellend",
  "bender",
  "beotch",
  "bestiality",
  "bi+ch",
  "biatch",
  "bicurious",
  "big black",
  "big breasts",
  "big knockers",
  "big tits",
  "bigbastard",
  "bigbutt",
  "bigtits",
  "birdlock",
  "bisexual",
  "bi-sexual",
  "bitch",
  "bitch tit",
  "bitchass",
  "bitched",
  "bitcher",
  "bitchers",
  "bitches",
  "bitchez",
  "bitchin",
  "bitching",
  "bitchtits",
  "bitchy",
  "black cock",
  "blonde action",
  "blonde on blonde action",
  "bloodclaat",
  "blow job",
  "blow me",
  "blow mud",
  "blow your load",
  "blowjob",
  "blowjobs",
  "blue waffle",
  "blumpkin",
  "boang",
  "bohunk",
  "boink",
  "boiolas",
  "bomd",
  "bondage",
  "boned",
  "boner",
  "boners",
  "boob",
  "boobies",
  "boobs",
  "booby",
  "booger",
  "bookie",
  "boong",
  "boonga",
  "booobs",
  "boooobs",
  "booooobs",
  "booooooobs",
  "bootee",
  "booty call",
  "breastjob",
  "breastlover",
  "breastman",
  "breeder",
  "brotherfucker",
  "brown showers",
  "brunette action",
  "buceta",
  "bukkake",
  "bulldike",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bullshits",
  "bullshitted",
  "bullturds",
  "bumblefuck",
  "bumclat",
  "bumfuck",
  "bunny fucker",
  "bust a load",
  "busty",
  "butchdike",
  "butchdyke",
  "butt fuck",
  "butt plug",
  "buttbang",
  "butt-bang",
  "buttcheeks",
  "buttface",
  "buttfuck",
  "butt-fuck",
  "buttfucka",
  "buttfucker",
  "butt-fucker",
  "butthead",
  "butthole",
  "buttman",
  "buttmuch",
  "buttmunch",
  "buttmuncher",
  "butt-pirate",
  "buttplug",
  "c.0.c.k",
  "c.o.c.k.",
  "c.u.n.t",
  "c0ck",
  "c-0-c-k",
  "c0cksucker",
  "cahone",
  "camel toe",
  "cameltoe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "cawk",
  "cervix",
  "chesticle",
  "chi-chi man",
  "chick with a dick",
  "child-fucker",
  "chin",
  "chinc",
  "chincs",
  "chink",
  "chinky",
  "choad",
  "choade",
  "chocolate rosebuds",
  "chode",
  "chodes",
  "circlejerk",
  "cl1t",
  "cleveland steamer",
  "clit",
  "clit licker",
  "clitface",
  "clitfuck",
  "clitoris",
  "clitorus",
  "clits",
  "clitty",
  "clitty litter",
  "clogwog",
  "clover clamps",
  "clunge",
  "clusterfuck",
  "cnut",
  "cock",
  "c-o-c-k",
  "cock pocket",
  "cock snot",
  "cock sucker",
  "cockass",
  "cockbite",
  "cockblock",
  "cockburger",
  "cockeye",
  "cockface",
  "cockfucker",
  "cockhead",
  "cockholster",
  "cockjockey",
  "cockknocker",
  "cockknoker",
  "cocklicker",
  "cocklover",
  "cocklump",
  "cockmaster",
  "cockmongler",
  "cockmongruel",
  "cockmonkey",
  "cockmunch",
  "cockmuncher",
  "cocknose",
  "cocknugget",
  "cocks",
  "cockshit",
  "cocksmith",
  "cocksmoke",
  "cocksmoker",
  "cocksniffer",
  "cocksucer",
  "cocksuck",
  "cocksuck ",
  "cocksucked",
  "cocksucker",
  "cock-sucker",
  "cocksuckers",
  "cocksucking",
  "cocksucks",
  "cocksuka",
  "cocksukka",
  "cockwaffle",
  "coffin dodger",
  "coital",
  "cokmuncher",
  "coksucka",
  "condom",
  "coochie",
  "coochy",
  "coon",
  "coonnass",
  "coons",
  "cooter",
  "cop some wood",
  "coprolagnia",
  "coprophilia",
  "corksucker",
  "cornhole",
  "corp whore",
  "crackwhore",
  "crack-whore",
  "creampie",
  "crotte",
  "cum",
  "cum chugger",
  "cum dumpster",
  "cum freak",
  "cum guzzler",
  "cumbubble",
  "cumdump",
  "cumdumpster",
  "cumguzzler",
  "cumjockey",
  "cummer",
  "cummin",
  "cumming",
  "cums",
  "cumshot",
  "cumshots",
  "cumslut",
  "cumstain",
  "cumtart",
  "cunilingus",
  "cunillingus",
  "cunn",
  "cunnie",
  "cunnilingus",
  "cunntt",
  "cunny",
  "cunt",
  "c-u-n-t",
  "cunt hair",
  "cuntass",
  "cuntbag",
  "cuntface",
  "cuntfuck",
  "cuntfucker",
  "cunthole",
  "cunthunter",
  "cuntlick",
  "cuntlick ",
  "cuntlicker",
  "cuntlicker ",
  "cuntlicking",
  "cuntrag",
  "cunts",
  "cuntsicle",
  "cuntslut",
  "cunt-struck",
  "cuntsucker",
  "cyalis",
  "cyberfuc",
  "cyberfuck",
  "cyberfucked",
  "cyberfucker",
  "cyberfuckers",
  "cyberfucking",
  "cybersex",
  "d0ng",
  "d0uch3",
  "d0uche",
  "d1ck",
  "d1ld0",
  "d1ldo",
  "darkie",
  "date rape",
  "daterape",
  "dawgie-style",
  "deep throat",
  "deepthroat",
  "deggo",
  "dendrophilia",
  "dick",
  "dick head",
  "dick hole",
  "dick shy",
  "dickbag",
  "dickbeaters",
  "dickbrain",
  "dickdipper",
  "dickface",
  "dickflipper",
  "dickfuck",
  "dickfucker",
  "dickhead",
  "dickheads",
  "dickhole",
  "dickish",
  "dick-ish",
  "dickjuice",
  "dickmilk",
  "dickmonger",
  "dickripper",
  "dicks",
  "dicksipper",
  "dickslap",
  "dick-sneeze",
  "dicksucker",
  "dicksucking",
  "dicktickler",
  "dickwad",
  "dickweasel",
  "dickweed",
  "dickwhipper",
  "dickwod",
  "dickzipper",
  "dike",
  "dildo",
  "dildos",
  "diligaf",
  "dillweed",
  "dink",
  "dinks",
  "dipship",
  "dipshit",
  "dirsa",
  "dirty pillows",
  "dirty sanchez",
  "dlck",
  "dog style",
  "dog-fucker",
  "doggie style",
  "doggiestyle",
  "doggie-style",
  "doggin",
  "dogging",
  "doggy style",
  "doggystyle",
  "doggy-style",
  "domination",
  "dominatrix",
  "dommes",
  "dong",
  "doochbag",
  "doosh",
  "double dong",
  "double penetration",
  "doublelift",
  "douch3",
  "douche",
  "douchebag",
  "douchebags",
  "douche-fag",
  "douchewaffle",
  "douchey",
  "dp action",
  "drunk",
  "dry hump",
  "duche",
  "dumbcunt",
  "dumbfuck",
  "dumbshit",
  "dumshit",
  "dykes",
  "eat a dick",
  "eat hair pie",
  "eat my ass",
  "eatpussy",
  "ecchi",
  "ejaculate",
  "ejaculated",
  "ejaculates",
  "ejaculating",
  "ejaculatings",
  "ejaculation",
  "ejakulate",
  "enlargement",
  "erect",
  "erection",
  "erotic",
  "erotism",
  "escort",
  "essohbee",
  "eunuch",
  "extacy",
  "extasy",
  "f u c k",
  "f u c k e r",
  "f.u.c.k",
  "f_u_c_k",
  "f4nny",
  "facefucker",
  "facial",
  "fack",
  "fag",
  "fagbag",
  "fagfucker",
  "fagg",
  "fagged",
  "fagging",
  "faggit",
  "faggitt",
  "faggot",
  "faggotcock",
  "faggots",
  "faggs",
  "fagot",
  "fagots",
  "fags",
  "fagtard",
  "faig",
  "faigt",
  "fannybandit",
  "fannyflaps",
  "fannyfucker",
  "fartknocker",
  "fastfuck",
  "fatass",
  "fatfuck",
  "fatfucker",
  "fcuk",
  "fcuker",
  "fcuking",
  "female squirting",
  "femdom",
  "fingerbang",
  "fingerfuck",
  "fingerfuck ",
  "fingerfucked",
  "fingerfucker",
  "fingerfucker ",
  "fingerfuckers",
  "fingerfucking",
  "fingerfucks",
  "fingering",
  "fist fuck",
  "fisted",
  "fistfuck",
  "fistfucked",
  "fistfucker",
  "fistfucker ",
  "fistfuckers",
  "fistfucking",
  "fistfuckings",
  "fistfucks",
  "fisting",
  "fisty",
  "flamer",
  "flange",
  "fleshflute",
  "fondle",
  "fooker",
  "foot fetish",
  "footfuck",
  "footfucker",
  "footjob",
  "footlicker",
  "foreskin",
  "freakfuck",
  "freakyfucker",
  "freefuck",
  "freex",
  "frigg",
  "frigga",
  "fuck",
  "f-u-c-k",
  "fuck buttons",
  "fuck hole",
  "fuck off",
  "fuck puppet",
  "fuck trophy",
  "fuck yo mama",
  "fuck you",
  "fucka",
  "fuckass",
  "fuck-ass",
  "fuckbag",
  "fuck-bitch",
  "fuckboy",
  "fuckbrain",
  "fuckbutt",
  "fuckbutter",
  "fucked",
  "fuckedup",
  "fucker",
  "fuckers",
  "fuckersucker",
  "fuckface",
  "fuckfreak",
  "fuckhead",
  "fuckheads",
  "fuckher",
  "fuckhole",
  "fuckin",
  "fucking",
  "fuckingbitch",
  "fuckings",
  "fuckingshitmotherfucker",
  "fuckme",
  "fuckme ",
  "fuckmeat",
  "fuckmehard",
  "fuckmonkey",
  "fucknugget",
  "fucknut",
  "fucknutt",
  "fuckoff",
  "fucks",
  "fuckstick",
  "fucktard",
  "fuck-tard",
  "fucktards",
  "fucktart",
  "fucktoy",
  "fucktwat",
  "fuckup",
  "fuckwad",
  "fuckwhit",
  "fuckwhore",
  "fuckwit",
  "fuckwitt",
  "fuckyou",
  "fudge packer",
  "fudgepacker",
  "fudge-packer",
  "fuker",
  "fukker",
  "fukkers",
  "fukkin",
  "fuks",
  "fukwhit",
  "fukwit",
  "futanari",
  "fux0r",
  "fvck",
  "fxck",
  "gang bang",
  "gangbang",
  "gang-bang",
  "gangbanged",
  "gangbangs",
  "ganja",
  "gassy ass",
  "gay sex",
  "gayass",
  "gaybob",
  "gaydo",
  "gayfuck",
  "gayfuckist",
  "gaylord",
  "gays",
  "gaysex",
  "gaytard",
  "gaywad",
  "gender bender",
  "genitals",
  "giant cock",
  "gigolo",
  "ginger",
  "gippo",
  "girl on",
  "girl on top",
  "girls gone wild",
  "goddamnmuthafucker",
  "gokkun",
  "golden shower",
  "goldenshower",
  "golliwog",
  "gonorrehea",
  "goo girl",
  "gooch",
  "goodpoop",
  "gook",
  "gooks",
  "goregasm",
  "gotohell",
  "grope",
  "group sex",
  "gspot",
  "g-spot",
  "gtfo",
  "guido",
  "h0m0",
  "h0mo",
  "ham flap",
  "hand job",
  "handjob",
  "hard core",
  "hard on",
  "hardcoresex",
  "headfuck",
  "hentai",
  "herp",
  "herpes",
  "herpy",
  "heshe",
  "he-she",
  "hitler",
  "hom0",
  "homey",
  "homo",
  "homodumbshit",
  "homoerotic",
  "homoey",
  "honkey",
  "honky",
  "hooch",
  "hookah",
  "hooker",
  "hoor",
  "hootch",
  "hooter",
  "hooters",
  "hore",
  "horniest",
  "horny",
  "hot carl",
  "hot chick",
  "hotpussy",
  "hotsex",
  "how to kill",
  "how to murdep",
  "how to murder",
  "hump",
  "humped",
  "humping",
  "hussy",
  "hymen",
  "iberian slap",
  "injun",
  "intercourse",
  "j3rk0ff",
  "jack off",
  "jackass",
  "jackasses",
  "jackhole",
  "jackoff",
  "jack-off",
  "jaggi",
  "jagoff",
  "jail bait",
  "jailbait",
  "jerk off",
  "jerk0ff",
  "jerkass",
  "jerked",
  "jerkoff",
  "jerk-off",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "jism",
  "jiz",
  "jizm",
  "jizz",
  "jizzed",
  "juggs",
  "jungle bunny",
  "junglebunny",
  "junkie",
  "junky",
  "kafir",
  "kawk",
  "kike",
  "kikes",
  "kill",
  "kinbaku",
  "kinkster",
  "kinky",
  "kkk",
  "klan",
  "knob",
  "knob end",
  "knobbing",
  "knobead",
  "knobed",
  "knobend",
  "knobhead",
  "knobjocky",
  "knobjokey",
  "kondum",
  "kondums",
  "kooch",
  "kooches",
  "kootch",
  "kummer",
  "kumming",
  "kunilingus",
  "l3i+ch",
  "l3itch",
  "leather restraint",
  "leather straight jacket",
  "lemon party",
  "lesbian",
  "lesbians",
  "lesbo",
  "lesbos",
  "lezbian",
  "lezbians",
  "lezbo",
  "lezbos",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "mafugly",
  "make me come",
  "male squirting",
  "masochist",
  "masterb8",
  "masterbat",
  "masterbat3",
  "masterbate",
  "master-bate",
  "masterbating",
  "masterbation",
  "masterbations",
  "masturbate",
  "masturbating",
  "masturbation",
  "mcfagget",
  "menage a trois",
  "menses",
  "menstruate",
  "menstruation",
  "m-fucking",
  "mick",
  "middle finger",
  "milf",
  "minge",
  "minger",
  "missionary position",
  "mof0",
  "mofo",
  "mo-fo",
  "moo moo foo foo",
  "moolie",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "motherfuck",
  "motherfucka",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "mtherfucker",
  "mthrfucker",
  "mthrfucking",
  "muff",
  "muff diver",
  "muff puff",
  "muffdiver",
  "muffdiving",
  "munging",
  "munter",
  "muthafecker",
  "muthafuckaz",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "mutherfucking",
  "muthrfucking",
  "n1gga",
  "n1gger",
  "nambla",
  "napalm",
  "nappy",
  "nawashi",
  "nazi",
  "nazism",
  "need the dick",
  "negro",
  "neonazi",
  "nig nog",
  "nigaboo",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggas",
  "niggaz",
  "nigger",
  "niggers",
  "niggle",
  "niglet",
  "nig-nog",
  "nimphomania",
  "ninny",
  "nob jokey",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "nsfw images",
  "numbnuts",
  "nut butter",
  "nut sack",
  "nutsack",
  "nympho",
  "nymphomania",
  "octopussy",
  "omorashi",
  "one cup two girls",
  "one guy one jar",
  "oral",
  "orally",
  "organ",
  "orgasim",
  "orgasims",
  "orgasm",
  "orgasmic",
  "orgasms",
  "orgies",
  "orgy",
  "ovary",
  "ovum",
  "ovums",
  "p.u.s.s.y.",
  "p0rn",
  "paddy",
  "panooch",
  "pastie",
  "pecker",
  "peckerhead",
  "pegging",
  "penetrate",
  "penetration",
  "penial",
  "penile",
  "penis",
  "penisbanger",
  "penisfucker",
  "penispuffer",
  "perversion",
  "phalli",
  "phallic",
  "phone sex",
  "phonesex",
  "phuck",
  "phuk",
  "phuked",
  "phuking",
  "phukked",
  "phukking",
  "phuks",
  "phuq",
  "piece of shit",
  "pigfucker",
  "pikey",
  "pillowbiter",
  "pimp",
  "pimpis",
  "pinko",
  "piss",
  "piss off",
  "piss pig",
  "pisser",
  "pissers",
  "pissflaps",
  "pissoff",
  "piss-off",
  "pisspig",
  "playboy",
  "pleasure chest",
  "pms",
  "polack",
  "pole smoker",
  "polesmoker",
  "pollock",
  "ponyplay",
  "poon",
  "poonani",
  "poonany",
  "poontang",
  "poop chute",
  "poopchute",
  "poopuncher",
  "porch monkey",
  "porchmonkey",
  "porn",
  "porno",
  "pornography",
  "pornos",
  "prick",
  "pricks",
  "prickteaser",
  "prig",
  "prince albert piercing",
  "prod",
  "pron",
  "prostitute",
  "prude",
  "pube",
  "pubes",
  "pubic",
  "pubis",
  "punani",
  "punanny",
  "punany",
  "punkass",
  "punky",
  "punta",
  "puss",
  "pusse",
  "pussi",
  "pussies",
  "pussy",
  "pussy fart",
  "pussy palace",
  "pussylicking",
  "pussypounder",
  "pussys",
  "pust",
  "puto",
  "queaf",
  "queef",
  "queer",
  "queerbait",
  "queerhole",
  "queero",
  "queers",
  "quicky",
  "quim",
  "racy",
  "raghead",
  "raging boner",
  "rape",
  "raped",
  "raper",
  "rapey",
  "raping",
  "rapist",
  "raunch",
  "reefer",
  "reetard",
  "reich",
  "renob",
  "retard",
  "retarded",
  "reverse cowgirl",
  "revue",
  "rimjaw",
  "rimjob",
  "rimming",
  "ritard",
  "rtard",
  "r-tard",
  "rump",
  "rumprammer",
  "ruski",
  "rusty trombone",
  "s&m",
  "s.h.i.t.",
  "s.o.b.",
  "s_h_i_t",
  "s0b",
  "sambo",
  "sand nigger",
  "sandnigger",
  "sanger",
  "santorum",
  "sausage queen",
  "scantily",
  "schizo",
  "schlong",
  "scissoring",
  "scroat",
  "scrog",
  "scrot",
  "scrote",
  "scrotum",
  "scrud",
  "seamen",
  "seduce",
  "seks",
  "semen",
  "sex",
  "sexo",
  "sexual",
  "sexy",
  "sh!+",
  "sh!t",
  "sh1t",
  "s-h-1-t",
  "shagger",
  "shaggin",
  "shagging",
  "shamedame",
  "shaved beaver",
  "shaved pussy",
  "shemale",
  "shi+",
  "shibari",
  "shirt lifter",
  "s-h-i-t",
  "shit fucker",
  "shitcunt",
  "shitdick",
  "shitfuck",
  "shota",
  "shrimping",
  "skag",
  "skank",
  "skullfuck",
  "slag",
  "slanteye",
  "slut bucket",
  "slutbag",
  "slutdumper",
  "slutkiss",
  "smeg",
  "smegma",
  "snatch",
  "snowballing",
  "snuff",
  "s-o-b",
  "son of a bitch",
  "son of a whore",
  "son-of-a-bitch",
  "souse",
  "soused",
  "spac",
  "spic",
  "spick",
  "spiks",
  "splooge",
  "splooge moose",
  "spooge",
  "spread legs",
  "spunk",
  "stiffy",
  "strapon",
  "strappado",
  "strip",
  "strip club",
  "style doggy",
  "suckass",
  "suicide girls",
  "sultry women",
  "sumofabiatch",
  "swastika",
  "swinger",
  "t1tt1e5",
  "t1tties",
  "tawdry",
  "tea bagging",
  "teabagging",
  "teets",
  "teste",
  "testee",
  "testes",
  "testical",
  "testicle",
  "testis",
  "threesome",
  "throating",
  "thundercunt",
  "tight white",
  "tit wank",
  "titfuck",
  "titi",
  "tities",
  "tits",
  "titt",
  "tittie5",
  "tittiefucker",
  "titties",
  "titty",
  "tittyfuck",
  "tittyfucker",
  "tittywank",
  "titwank",
  "toots",
  "tosser",
  "towelhead",
  "tramp",
  "tribadism",
  "trumped",
  "tub girl",
  "tubgirl",
  "tw4t",
  "twat",
  "twathead",
  "twatlips",
  "twats",
  "twatty",
  "twatwaffle",
  "twink",
  "twinkie",
  "two fingers",
  "two fingers with tongue",
  "two girls one cup",
  "twunt",
  "twunter",
  "unclefucker",
  "upskirt",
  "urethra play",
  "urophilia",
  "v14gra",
  "v1gra",
  "vagina",
  "vajayjay",
  "va-j-j",
  "venus mound",
  "viagra",
  "vibrator",
  "vixen",
  "vjayjay",
  "vorarephilia",
  "voyeur",
  "vulgar",
  "vulva",
  "w00se",
  "wanker",
  "wankjob",
  "wanky",
  "wazoo",
  "weiner",
  "wetback",
  "wh0re",
  "wh0reface",
  "whoar",
  "whoralicious",
  "whore",
  "whorealicious",
  "whorebag",
  "whored",
  "whoreface",
  "whorehopper",
  "whorehouse",
  "whores",
  "whoring",
  "wigger",
  "willies",
  "willy",
  "window licker",
  "wiseass",
  "wiseasses",
  "wrapping men",
  "wrinkled starfish",
  "xrated",
  "x-rated",
  "xxx",
  "yaoi",
  "yellow showers",
  "yiffy",
  "yobbo",
  "zoophile",
];